import 'dotenv/config'
import { prisma } from '../src/lib/prisma'
import { TicketStatus, TicketCategory } from '@prisma/client'

const tickets = [
  // ── Technical Questions ────────────────────────────────────────────────────
  {
    fromName: 'James Carter',
    fromEmail: 'james.carter@outlook.com',
    subject: 'App crashes on iOS 17 when opening notifications',
    body: 'Hi, every time I tap a push notification the app crashes immediately. I\'m on iPhone 14 Pro running iOS 17.2. This started after your last update. Please fix this ASAP.',
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(1),
  },
  {
    fromName: 'Priya Nair',
    fromEmail: 'priya.nair@gmail.com',
    subject: 'Two-factor authentication code not arriving by SMS',
    body: 'I set up 2FA last week and the SMS codes stopped arriving yesterday. I\'ve verified my phone number is correct. Could you check if there\'s an issue on your end?',
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(2),
  },
  {
    fromName: 'Luca Ferretti',
    fromEmail: 'luca.ferretti@fastmail.com',
    subject: 'CSV export produces corrupted file',
    body: 'When I export my data as CSV the downloaded file is empty except for the header row. I\'ve tried Chrome and Firefox. My account has about 3,000 records.',
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(3),
  },
  {
    fromName: 'Sofia Andersen',
    fromEmail: 'sofia.andersen@protonmail.com',
    subject: 'Dashboard charts not loading — blank white boxes',
    body: 'The analytics charts on my dashboard have been showing as empty white boxes for the past two days. My colleagues on the same plan can see theirs fine. Tried clearing cache.',
    status: TicketStatus.resolved,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(10),
  },
  {
    fromName: 'Kwame Asante',
    fromEmail: 'k.asante@businessmail.com',
    subject: 'API rate limit errors despite being on Pro plan',
    body: 'We\'re hitting 429 errors on the API even though our Pro plan says unlimited requests. Our integration makes about 500 calls per minute. Is there a per-minute cap I\'m not aware of?',
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(1),
  },
  {
    fromName: 'Hannah Müller',
    fromEmail: 'h.muller@webde.de',
    subject: 'Password reset link expires before I can use it',
    body: 'I click the reset link from the email and it says "link expired" even if I click it within 30 seconds. I\'ve requested the reset three times now.',
    status: TicketStatus.resolved,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(14),
  },
  {
    fromName: 'Marco Delgado',
    fromEmail: 'marco.delgado@icloud.com',
    subject: 'Zapier integration stops working after OAuth reconnect',
    body: 'Every time I reconnect the OAuth connection in Zapier, my existing Zaps break and need to be reconfigured. This has happened four times this month.',
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(5),
  },
  {
    fromName: 'Yuki Tanaka',
    fromEmail: 'yuki.tanaka@yahoo.co.jp',
    subject: 'Bulk upload silently fails for files over 5 MB',
    body: 'I upload a 7 MB spreadsheet and the progress bar completes but no records appear. Files under 5 MB work fine. Is there a file size limit that isn\'t documented?',
    status: TicketStatus.closed,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(30),
  },
  {
    fromName: 'Aisha Okonkwo',
    fromEmail: 'aisha.okonkwo@gmail.com',
    subject: 'Calendar sync with Google Calendar shows wrong timezone',
    body: 'My events are appearing three hours off in Google Calendar. I\'m in EST and I\'ve confirmed my timezone is set correctly in both apps.',
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(2),
  },
  {
    fromName: 'Ethan Brooks',
    fromEmail: 'ethan.brooks@hotmail.com',
    subject: 'Search returns no results for exact phrase matches',
    body: 'If I search for an exact phrase in quotes I always get zero results, but searching individual words works. Example: "quarterly report" returns nothing but quarterly and report return hundreds.',
    status: TicketStatus.resolved,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(21),
  },

  // ── Refund Requests ────────────────────────────────────────────────────────
  {
    fromName: 'Olivia Chen',
    fromEmail: 'olivia.chen@gmail.com',
    subject: 'Charged twice for March subscription',
    body: 'I was billed $49 twice on March 3rd. I can see two identical transactions on my credit card statement. Please refund the duplicate charge.',
    status: TicketStatus.open,
    category: TicketCategory.refund_request,
    createdAt: daysAgo(3),
  },
  {
    fromName: 'Daniel Park',
    fromEmail: 'daniel.park@naver.com',
    subject: 'Refund for annual plan — cancelling due to job loss',
    body: 'Unfortunately I\'ve been laid off and can no longer afford the annual subscription. I signed up 6 weeks ago and haven\'t used the service much. I\'d like a prorated refund for the remaining 10 months.',
    status: TicketStatus.open,
    category: TicketCategory.refund_request,
    createdAt: daysAgo(1),
  },
  {
    fromName: 'Rachel Thompson',
    fromEmail: 'rachel.t@outlook.com',
    subject: 'Accidental upgrade to Enterprise — need immediate refund',
    body: 'I was trying to view the pricing page and accidentally clicked "Upgrade" on the Enterprise plan. I was charged $299. Please refund immediately — I\'m on the right plan already.',
    status: TicketStatus.resolved,
    category: TicketCategory.refund_request,
    createdAt: daysAgo(8),
  },
  {
    fromName: 'Carlos Mendoza',
    fromEmail: 'c.mendoza@empresa.mx',
    subject: 'Service was down for 5 days — requesting SLA credit',
    body: 'Your service was inaccessible for our team from the 12th to the 17th. Our Pro plan SLA guarantees 99.9% uptime. I\'d like a credit for the affected period.',
    status: TicketStatus.open,
    category: TicketCategory.refund_request,
    createdAt: daysAgo(4),
  },
  {
    fromName: 'Fatima Al-Hassan',
    fromEmail: 'fatima.alhassan@hotmail.com',
    subject: 'Duplicate charge after plan change',
    body: 'I upgraded from Starter to Pro mid-month and was charged the full amount for both plans. I expected a prorated credit. Please fix the billing.',
    status: TicketStatus.closed,
    category: TicketCategory.refund_request,
    createdAt: daysAgo(45),
  },
  {
    fromName: 'Tom Harrington',
    fromEmail: 'tom.harrington@btinternet.com',
    subject: 'Team member seat charged after I removed them',
    body: 'I removed a team member on the 1st of the month but was still charged for their seat on the next invoice. Please refund the extra seat charge.',
    status: TicketStatus.resolved,
    category: TicketCategory.refund_request,
    createdAt: daysAgo(18),
  },
  {
    fromName: 'Mei Lin',
    fromEmail: 'mei.lin@163.com',
    subject: 'Purchased wrong plan — need refund and help switching',
    body: 'I purchased the Business plan instead of the Pro plan by mistake. The pricing page was a bit confusing. Can I get a refund for the difference and be moved to Pro?',
    status: TicketStatus.open,
    category: TicketCategory.refund_request,
    createdAt: daysAgo(2),
  },
  {
    fromName: 'Ahmed Khalil',
    fromEmail: 'ahmed.khalil@gmail.com',
    subject: 'Charged after cancellation confirmation',
    body: 'I cancelled my subscription on February 28th and received a cancellation confirmation email, yet I was still charged on March 1st. Please refund the unauthorized charge.',
    status: TicketStatus.open,
    category: TicketCategory.refund_request,
    createdAt: daysAgo(6),
  },
  {
    fromName: 'Natalie Rousseau',
    fromEmail: 'n.rousseau@laposte.net',
    subject: 'Annual renewal charge I didn\'t authorize',
    body: 'My annual subscription renewed without warning. I never received the 30-day renewal reminder that your terms of service promise. Please refund the full year — I want to cancel.',
    status: TicketStatus.closed,
    category: TicketCategory.refund_request,
    createdAt: daysAgo(60),
  },
  {
    fromName: 'Ben Okafor',
    fromEmail: 'ben.okafor@yahoo.com',
    subject: 'Partial refund for unused add-on',
    body: 'I purchased the Advanced Reporting add-on for $29/month but it doesn\'t integrate with Salesforce as advertised. I\'d like a refund for the last two months.',
    status: TicketStatus.resolved,
    category: TicketCategory.refund_request,
    createdAt: daysAgo(12),
  },

  // ── General Questions ─────────────────────────────────────────────────────
  {
    fromName: 'Emma Williams',
    fromEmail: 'emma.williams@gmail.com',
    subject: 'How do I transfer ownership of my account?',
    body: 'I\'m leaving the company and need to transfer the account to my colleague Sarah Johnson. She already has a user account. What\'s the process for transferring ownership?',
    status: TicketStatus.resolved,
    category: TicketCategory.general_question,
    createdAt: daysAgo(9),
  },
  {
    fromName: 'Raj Patel',
    fromEmail: 'raj.patel@infosys.com',
    subject: 'Do you offer a discount for non-profits?',
    body: 'We\'re a registered 501(c)(3) non-profit organization. Do you have a non-profit pricing tier? We currently use the Basic plan for 12 users.',
    status: TicketStatus.open,
    category: TicketCategory.general_question,
    createdAt: daysAgo(1),
  },
  {
    fromName: 'Laura Bianchi',
    fromEmail: 'l.bianchi@virgilio.it',
    subject: 'Is there a mobile app for Android?',
    body: 'I can only find the iOS app on the website. Is there an Android version? If not, are there plans to develop one? Our team is split between iOS and Android.',
    status: TicketStatus.closed,
    category: TicketCategory.general_question,
    createdAt: daysAgo(40),
  },
  {
    fromName: 'Jake Morrison',
    fromEmail: 'jake.morrison@protonmail.com',
    subject: 'How long is data retained after account cancellation?',
    body: 'If we cancel our subscription, how long do you keep our data before deleting it? And is there a way to export everything before we leave?',
    status: TicketStatus.resolved,
    category: TicketCategory.general_question,
    createdAt: daysAgo(16),
  },
  {
    fromName: 'Chloe Dubois',
    fromEmail: 'chloe.dubois@orange.fr',
    subject: 'Can I use the same account on multiple devices?',
    body: 'I work from both a laptop and a desktop. Can I be logged into both at the same time, or do I need to log out from one before using the other?',
    status: TicketStatus.resolved,
    category: TicketCategory.general_question,
    createdAt: daysAgo(22),
  },
  {
    fromName: 'Dmitri Volkov',
    fromEmail: 'dmitri.volkov@mail.ru',
    subject: 'Is GDPR-compliant data processing available?',
    body: 'Our legal team requires a Data Processing Agreement (DPA) for GDPR compliance. Do you offer one? Where can I find it or request it?',
    status: TicketStatus.open,
    category: TicketCategory.general_question,
    createdAt: daysAgo(3),
  },
  {
    fromName: 'Isabel Santos',
    fromEmail: 'isabel.santos@gmail.com',
    subject: 'What payment methods do you accept?',
    body: 'We\'re based in Brazil and would like to pay by bank transfer (boleto). Do you accept this? Also, do you accept payments in BRL?',
    status: TicketStatus.closed,
    category: TicketCategory.general_question,
    createdAt: daysAgo(35),
  },
  {
    fromName: 'Patrick O\'Brien',
    fromEmail: 'p.obrien@eircom.ie',
    subject: 'How do I add a custom domain to my workspace?',
    body: 'I\'d like my team\'s login page to appear at support.mycompany.com instead of the default URL. Is custom domain configuration available on our Business plan?',
    status: TicketStatus.open,
    category: TicketCategory.general_question,
    createdAt: daysAgo(4),
  },
  {
    fromName: 'Zara Khan',
    fromEmail: 'zara.khan@hotmail.co.uk',
    subject: 'Difference between admin and owner roles?',
    body: 'I\'m setting up roles for my team and I\'m not clear on the difference between "Admin" and "Owner" access levels. Can you explain what each role can and cannot do?',
    status: TicketStatus.resolved,
    category: TicketCategory.general_question,
    createdAt: daysAgo(11),
  },
  {
    fromName: 'Nathan Boateng',
    fromEmail: 'nathan.boateng@gmail.com',
    subject: 'Do you have a free trial for the Enterprise plan?',
    body: 'We\'re evaluating your platform for our 200-person company. Is there a way to trial the Enterprise plan features before committing? We\'re currently on Business.',
    status: TicketStatus.open,
    category: TicketCategory.general_question,
    createdAt: daysAgo(2),
  },
  {
    fromName: 'Ingrid Larsen',
    fromEmail: 'ingrid.larsen@telenor.no',
    subject: 'Can I change my billing cycle from monthly to annual?',
    body: 'I\'ve been on monthly billing for 6 months and would like to switch to annual to save money. Is this possible mid-cycle and will I get a prorated credit?',
    status: TicketStatus.open,
    category: TicketCategory.general_question,
    createdAt: daysAgo(1),
  },
  {
    fromName: 'Victor Osei',
    fromEmail: 'victor.osei@gmail.com',
    subject: 'How do I invite external collaborators without full accounts?',
    body: 'I want to share a project view with a client without giving them a full account. Do you support guest or read-only access for external users?',
    status: TicketStatus.closed,
    category: TicketCategory.general_question,
    createdAt: daysAgo(50),
  },
  {
    fromName: 'Amelia Johansson',
    fromEmail: 'amelia.j@telia.se',
    subject: 'Is there a keyboard shortcut reference guide?',
    body: 'I use keyboard shortcuts heavily and would love a full list of all available shortcuts. I found a few by accident but haven\'t seen a comprehensive guide.',
    status: TicketStatus.resolved,
    category: TicketCategory.general_question,
    createdAt: daysAgo(13),
  },
  {
    fromName: 'Wei Zhang',
    fromEmail: 'wei.zhang@qq.com',
    subject: 'Is there a Chinese language interface available?',
    body: 'Our team is primarily Mandarin-speaking. Does the platform support a Simplified Chinese UI? If not, is there a localization roadmap?',
    status: TicketStatus.open,
    category: TicketCategory.general_question,
    createdAt: daysAgo(5),
  },
  {
    fromName: 'Freya Nielsen',
    fromEmail: 'freya.nielsen@gmail.dk',
    subject: 'Notification emails going to spam folder',
    body: 'All emails from your service land in my spam folder. I\'ve added the address to my safe senders list but they still go to spam. Is there a way to whitelist your sending domain?',
    status: TicketStatus.open,
    category: TicketCategory.general_question,
    createdAt: daysAgo(3),
  },

  // ── Mixed / Uncategorised ─────────────────────────────────────────────────
  {
    fromName: 'Samuel Adeyemi',
    fromEmail: 'samuel.adeyemi@outlook.com',
    subject: 'Account locked after too many login attempts',
    body: 'I forgot my password and tried several times. Now the account is locked. The reset email isn\'t arriving either. I need urgent access — I have a client call in an hour.',
    status: TicketStatus.resolved,
    category: null,
    createdAt: daysAgo(7),
  },
  {
    fromName: 'Clara Hoffman',
    fromEmail: 'clara.hoffman@gmx.de',
    subject: 'Merge two separate accounts into one',
    body: 'I created two accounts by mistake — one with my personal email and one with my work email. Is it possible to merge them so all my data is in one place?',
    status: TicketStatus.open,
    category: null,
    createdAt: daysAgo(2),
  },
  {
    fromName: 'Leo Martins',
    fromEmail: 'leo.martins@uol.com.br',
    subject: 'Team workspace deleted by mistake — can it be restored?',
    body: 'One of my admins accidentally deleted our main workspace. All our project data and integrations were inside. Can you restore it from a backup? This is urgent.',
    status: TicketStatus.open,
    category: null,
    createdAt: daysAgo(1),
  },
  {
    fromName: 'Nadia Petrova',
    fromEmail: 'nadia.petrova@yandex.ru',
    subject: 'Invoice shows wrong company name',
    body: 'Our last three invoices show "Petrova Consulting" but we rebranded to "NP Solutions Ltd" two months ago. I updated the billing name in settings. Can you reissue the invoices?',
    status: TicketStatus.closed,
    category: null,
    createdAt: daysAgo(55),
  },
  {
    fromName: 'Owen Clarke',
    fromEmail: 'owen.clarke@sky.com',
    subject: 'Feature request: dark mode',
    body: 'I work long hours and a dark mode would really help with eye strain. Do you have this on the roadmap? Many of the tools I use already support it.',
    status: TicketStatus.closed,
    category: null,
    createdAt: daysAgo(42),
  },

  // ── More technical ────────────────────────────────────────────────────────
  {
    fromName: 'Grace Oduya',
    fromEmail: 'grace.oduya@gmail.com',
    subject: 'SSO login broken for our Okta integration',
    body: 'Since last Tuesday our team can\'t log in via Okta SSO. We get "authentication failed" even though nothing changed on our side. About 80 people are affected.',
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(1),
  },
  {
    fromName: 'Hugo Lefebvre',
    fromEmail: 'hugo.lefebvre@sfr.fr',
    subject: 'Webhook events arriving out of order',
    body: 'Our webhook handler is receiving events with timestamps out of sequence, which is causing data integrity issues in our CRM. Is there a way to guarantee delivery order?',
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(3),
  },
  {
    fromName: 'Tina Svensson',
    fromEmail: 'tina.svensson@live.se',
    subject: 'Images uploaded in comments are not displaying',
    body: 'When team members paste or upload images in ticket comments, they show as broken image icons. This started happening around three days ago.',
    status: TicketStatus.resolved,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(15),
  },
  {
    fromName: 'Andre Kimura',
    fromEmail: 'andre.kimura@gmail.com',
    subject: 'Audit log shows actions from an IP I don\'t recognise',
    body: 'I checked the audit log and see several export actions from an IP address (185.220.101.x) that isn\'t ours. Could our account have been compromised? Please advise urgently.',
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(1),
  },
  {
    fromName: 'Siobhan Murphy',
    fromEmail: 'siobhan.murphy@eircom.ie',
    subject: 'Report scheduler sends blank PDFs',
    body: 'I scheduled a weekly PDF summary report and the emails arrive but the attached PDF is blank — no data, just the header and footer. The same report generates correctly when run manually.',
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(4),
  },
  {
    fromName: 'Felix Wagner',
    fromEmail: 'felix.wagner@web.de',
    subject: 'Import from Trello fails at step 3 of 4',
    body: 'I\'m trying to import our Trello board (JSON export, about 2,400 cards). The import wizard gets to "Processing attachments" and then freezes. I\'ve waited 20 minutes.',
    status: TicketStatus.resolved,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(19),
  },
  {
    fromName: 'Anya Sharma',
    fromEmail: 'anya.sharma@rediffmail.com',
    subject: 'Custom fields not appearing in API responses',
    body: 'I added three custom fields to our ticket type last week but they don\'t appear in the REST API response for GET /tickets. The documentation says they should be included by default.',
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(2),
  },
  {
    fromName: 'Tyler Evans',
    fromEmail: 'tyler.evans@gmail.com',
    subject: 'Slack notifications stopped working after workspace rename',
    body: 'We renamed our Slack workspace last week and now the integration has stopped posting notifications. I\'ve tried reconnecting but it fails with a "workspace not found" error.',
    status: TicketStatus.resolved,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(17),
  },
  {
    fromName: 'Bianca Costa',
    fromEmail: 'bianca.costa@terra.com.br',
    subject: 'Pagination broken — page 2 shows same results as page 1',
    body: 'When I click "Next page" in the ticket list, the URL changes to ?page=2 but the exact same 25 results appear as on page 1. This makes it impossible to review older tickets.',
    status: TicketStatus.open,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(2),
  },
  {
    fromName: 'Marcus Hill',
    fromEmail: 'marcus.hill@hotmail.com',
    subject: 'Time tracking widget shows negative hours',
    body: 'The time tracking widget on several tickets is displaying negative values like "-2h 14m". I think it might be related to a timezone mismatch between my local time and the server.',
    status: TicketStatus.closed,
    category: TicketCategory.technical_question,
    createdAt: daysAgo(38),
  },
]

function daysAgo(n: number): Date {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d
}

async function main() {
  console.log(`Seeding ${tickets.length} tickets...`)
  const result = await prisma.ticket.createMany({ data: tickets })
  console.log(`Created ${result.count} tickets.`)
}

main()
  .catch((err) => {
    console.error(err)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
